services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - REPOSITORY_SQLITE_DB=/data/iwallpapers.db
      - SPIDER_STORE_DIR=/data
      - PROXY=${PROXY}
      - PYTHONDONTWRITEBYTECODE=1
      - WALLHAVEN_API_KEY=${WALLHAVEN_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - POSTGRES_DSN=${POSTGRES_DSN}
    restart: unless-stopped

  spider_wallhaven:
    build:
      context: .
      dockerfile: spiders/spider_wallhaven_Dockerfile
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - REPOSITORY_SQLITE_DB=/data/iwallpapers.db
      - SPIDER_STORE_DIR=/data
      - PROXY=${PROXY}
      - PYTHONDONTWRITEBYTECODE=1
      - WALLHAVEN_API_KEY=${WALLHAVEN_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CIVITAI_API_KEY=${CIVITAI_API_KEY}
      - POSTGRES_DSN=${POSTGRES_DSN}
    restart: unless-stopped

  spider_unsplash:
    build:
      context: .
      dockerfile: spiders/spider_unsplash_Dockerfile
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - REPOSITORY_SQLITE_DB=/data/iwallpapers.db
      - SPIDER_STORE_DIR=/data
      - PROXY=${PROXY}
      - PYTHONDONTWRITEBYTECODE=1
      - WALLHAVEN_API_KEY=${WALLHAVEN_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CIVITAI_API_KEY=${CIVITAI_API_KEY}
      - POSTGRES_DSN=${POSTGRES_DSN}
    restart: unless-stopped

  spider_civitai:
    build:
      context: .
      dockerfile: spiders/spider_civitai_Dockerfile
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - REPOSITORY_SQLITE_DB=/data/iwallpapers.db
      - SPIDER_STORE_DIR=/data
      - PROXY=${PROXY}
      - PYTHONDONTWRITEBYTECODE=1
      - WALLHAVEN_API_KEY=${WALLHAVEN_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CIVITAI_API_KEY=${CIVITAI_API_KEY}
      - POSTGRES_DSN=${POSTGRES_DSN}
    restart: unless-stopped

  spider_wallhere:
    build:
      context: .
      dockerfile: spiders/spider_wallhere_Dockerfile
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - REPOSITORY_SQLITE_DB=/data/iwallpapers.db
      - SPIDER_STORE_DIR=/data
      - PROXY=${PROXY}
      - PYTHONDONTWRITEBYTECODE=1
      - WALLHAVEN_API_KEY=${WALLHAVEN_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CIVITAI_API_KEY=${CIVITAI_API_KEY}
      - POSTGRES_DSN=${POSTGRES_DSN}
    restart: unless-stopped
